import { DateTime } from "luxon";
import type {
  ChatMessage,
  Club,
  ClubMembership,
  DropSlot,
  JoinRequest,
  Notification,
  PlaylistDraft,
  UserProfile,
} from "@/types/domain";

const now = () => DateTime.now().toUTC();
const iso = (offset: { days?: number; hours?: number; minutes?: number }) =>
  now().plus(offset).toISO();

export const demoUsers: UserProfile[] = [
  {
    id: "user-lena",
    clerkUserId: "demo_lena",
    displayName: "Lena Ortiz",
    initials: "LO",
    primaryEmail: "lena@example.com",
    plan: "middle",
    emailNotifications: true,
    themePreference: "system",
    skinPreference: "classic",
    createdAt: iso({ days: -120 }),
    updatedAt: iso({ days: -1 }),
  },
  {
    id: "user-marcus",
    clerkUserId: "demo_marcus",
    displayName: "Marcus Chen",
    initials: "MC",
    plan: "free",
    emailNotifications: true,
    themePreference: "system",
    skinPreference: "classic",
    createdAt: iso({ days: -100 }),
    updatedAt: iso({ days: -2 }),
  },
  {
    id: "user-priya",
    clerkUserId: "demo_priya",
    displayName: "Priya Shah",
    initials: "PS",
    plan: "entry",
    emailNotifications: true,
    themePreference: "system",
    skinPreference: "classic",
    createdAt: iso({ days: -80 }),
    updatedAt: iso({ days: -2 }),
  },
  {
    id: "user-theo",
    clerkUserId: "demo_theo",
    displayName: "Theo Brooks",
    initials: "TB",
    plan: "free",
    emailNotifications: false,
    themePreference: "system",
    skinPreference: "classic",
    createdAt: iso({ days: -55 }),
    updatedAt: iso({ days: -3 }),
  },
  {
    id: "user-maya",
    clerkUserId: "demo_maya",
    displayName: "Maya Ellis",
    initials: "ME",
    plan: "free",
    emailNotifications: true,
    themePreference: "system",
    skinPreference: "classic",
    createdAt: iso({ days: -28 }),
    updatedAt: iso({ hours: -8 }),
  },
];

export const demoClubs: Club[] = [
  {
    id: "club-needle",
    slug: "needle-exchange",
    name: "Needle Exchange",
    description: "One record-bin rabbit hole every Tuesday. No algorithms, just people with receipts.",
    visibility: "public",
    accent: "#ff5c35",
    memberCount: 12,
    rotationMemberIds: ["user-marcus", "user-priya", "user-theo", "user-lena"],
    currentTheme: {
      name: "Heatwave at midnight",
      guidance: "Songs that feel like the city is still radiating after dark.",
      version: 4,
      updatedAt: iso({ days: -3 }),
    },
    savedThemes: [{
      name: "The long way home",
      guidance: "Songs for taking one more block before turning toward the door.",
      version: 5,
      updatedAt: iso({ days: -1 }),
    }],
    schedule: {
      timezone: "America/Chicago",
      startsOn: "2026-01-06",
      localTime: "09:00",
      frequency: "weekly",
      interval: 1,
      weekdays: [2],
      rrule: "FREQ=WEEKLY;INTERVAL=1;BYDAY=TU",
      reminderOffsetsMinutes: [1440, 60],
      version: 3,
      paused: false,
    },
    activeDropId: "drop-next",
    custody: { status: "active", activeOwnerId: "user-lena", recoveryClaimantId: null },
    createdAt: iso({ days: -118 }),
    updatedAt: iso({ hours: -4 }),
  },
  {
    id: "club-sunday",
    slug: "sunday-service",
    name: "Sunday Service",
    description: "A soft landing for the end of the week: soul, ambient, gospel, and anything restorative.",
    visibility: "private",
    accent: "#6f7b45",
    memberCount: 7,
    rotationMemberIds: ["user-lena", "user-theo", "user-priya"],
    currentTheme: {
      name: "Windows open",
      guidance: "Music for the first warm morning after a long winter.",
      version: 2,
      updatedAt: iso({ days: -5 }),
    },
    schedule: {
      timezone: "America/Chicago",
      startsOn: "2026-02-01",
      localTime: "11:00",
      frequency: "weekly",
      interval: 1,
      weekdays: [7],
      rrule: "FREQ=WEEKLY;INTERVAL=1;BYDAY=SU",
      reminderOffsetsMinutes: [2880, 180],
      version: 1,
      paused: false,
    },
    activeDropId: "drop-sunday-next",
    custody: { status: "active", activeOwnerId: "user-priya", recoveryClaimantId: null },
    createdAt: iso({ days: -90 }),
    updatedAt: iso({ hours: -12 }),
  },
  {
    id: "club-afterhours",
    slug: "after-hours-department",
    name: "After Hours Department",
    description: "Club music for people who read the liner notes.",
    visibility: "public",
    accent: "#7c5cff",
    memberCount: 24,
    rotationMemberIds: ["user-priya", "user-marcus", "user-theo"],
    savedThemes: [{
      name: "Chrome and concrete",
      guidance: "Hard surfaces, bright reflections, no sunrise in sight.",
      version: 7,
      updatedAt: iso({ days: -1 }),
    }],
    schedule: {
      timezone: "America/New_York",
      startsOn: "2026-03-06",
      localTime: "17:30",
      frequency: "weekly",
      interval: 2,
      weekdays: [5],
      rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=FR",
      reminderOffsetsMinutes: [1440, 60],
      version: 2,
      paused: false,
    },
    activeDropId: "drop-after-next",
    custody: { status: "active", activeOwnerId: "user-priya", recoveryClaimantId: null },
    createdAt: iso({ days: -73 }),
    updatedAt: iso({ hours: -8 }),
  },
];

export const demoMemberships: ClubMembership[] = demoClubs.flatMap((club) =>
  club.rotationMemberIds.map((userId, index) => ({
    id: `${club.id}:${userId}`,
    clubId: club.id,
    userId,
    role:
      club.custody.activeOwnerId === userId
        ? "owner"
        : userId === "user-lena" && club.id === "club-sunday"
          ? "admin"
          : "member",
    status: "active",
    queuePaused: false,
    joinedAt: iso({ days: -60 + index }),
    updatedAt: iso({ days: -index }),
  })),
);

export const demoJoinRequests: JoinRequest[] = [
  {
    id: "join-maya-needle",
    clubId: "club-needle",
    userId: "user-maya",
    message: "I would love to bring a few left-field soul and jazz picks into the rotation.",
    status: "pending",
    createdAt: iso({ hours: -6 }),
    updatedAt: iso({ hours: -6 }),
  },
];

export const demoDrops: DropSlot[] = [
  {
    id: "drop-next",
    clubId: "club-needle",
    occurrenceKey: "club-needle:next:v3",
    scheduleVersion: 3,
    status: "scheduled",
    assignedUserId: "user-marcus",
    scheduledFor: iso({ days: 4 }),
    createdAt: iso({ days: -3 }),
    updatedAt: iso({ hours: -10 }),
  },
  {
    id: "drop-sunday-next",
    clubId: "club-sunday",
    occurrenceKey: "club-sunday:next:v1",
    scheduleVersion: 1,
    status: "scheduled",
    assignedUserId: "user-lena",
    scheduledFor: iso({ days: 2 }),
    playlist: {
      sourceDraftId: "draft-2",
      provider: "apple-music",
      providerPlaylistId: "pl.u-b3b8V4etKZA9p",
      canonicalUrl: "https://music.apple.com/us/playlist/pl.u-b3b8V4etKZA9p",
      embedUrl: "https://embed.music.apple.com/us/playlist/pl.u-b3b8V4etKZA9p",
      title: "Curtains moving",
      description: "A slow build from Alice Coltrane to Cleo Sol for a room that has nowhere to be.",
      metadata: {},
      theme: demoClubs[1].currentTheme,
    },
    createdAt: iso({ days: -5 }),
    updatedAt: iso({ hours: -2 }),
  },
  {
    id: "drop-after-next",
    clubId: "club-afterhours",
    occurrenceKey: "club-afterhours:next:v2",
    scheduleVersion: 2,
    status: "scheduled",
    assignedUserId: "user-priya",
    scheduledFor: iso({ days: 8 }),
    createdAt: iso({ days: -2 }),
    updatedAt: iso({ days: -1 }),
  },
  {
    id: "drop-sunburn",
    clubId: "club-needle",
    occurrenceKey: "club-needle:previous-1:v3",
    scheduleVersion: 3,
    status: "published",
    assignedUserId: "user-lena",
    scheduledFor: iso({ days: -3 }),
    publishedAt: iso({ days: -3 }),
    playlist: {
      provider: "spotify",
      providerPlaylistId: "37i9dQZF1DX4JAvHpjipBk",
      canonicalUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4JAvHpjipBk",
      embedUrl: "https://open.spotify.com/embed/playlist/37i9dQZF1DX4JAvHpjipBk?utm_source=generator&theme=0",
      versions: [
        {
          provider: "spotify",
          providerPlaylistId: "37i9dQZF1DX4JAvHpjipBk",
          canonicalUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4JAvHpjipBk",
          embedUrl: "https://open.spotify.com/embed/playlist/37i9dQZF1DX4JAvHpjipBk?utm_source=generator&theme=0",
        },
        {
          provider: "apple-music",
          providerPlaylistId: "pl.u-b3b8V4etKZA9p",
          canonicalUrl: "https://music.apple.com/us/playlist/pl.u-b3b8V4etKZA9p",
          embedUrl: "https://embed.music.apple.com/us/playlist/pl.u-b3b8V4etKZA9p",
        },
      ],
      title: "Sunburn after dark",
      description: "Sticky drums, scorched guitars, and synths that refuse to cool down.",
      metadata: { providerTitle: "New Music Friday", ownerName: "Spotify" },
      theme: demoClubs[0].currentTheme,
    },
    createdAt: iso({ days: -10 }),
    updatedAt: iso({ days: -3 }),
  },
  {
    id: "drop-neon",
    clubId: "club-needle",
    occurrenceKey: "club-needle:previous-2:v3",
    scheduleVersion: 3,
    status: "published",
    assignedUserId: "user-theo",
    scheduledFor: iso({ days: -10 }),
    publishedAt: iso({ days: -10 }),
    playlist: {
      provider: "apple-music",
      providerPlaylistId: "pl.2b0e6e332fdf4b7a91164da3162127b5",
      canonicalUrl: "https://music.apple.com/us/playlist/pl.2b0e6e332fdf4b7a91164da3162127b5",
      embedUrl: "https://embed.music.apple.com/us/playlist/pl.2b0e6e332fdf4b7a91164da3162127b5",
      title: "Neon receipts",
      description: "The sound of remembering where you were at 1:47 a.m.",
      metadata: { providerTitle: "danceXL" },
      theme: { ...demoClubs[0].currentTheme!, name: "Proof of a good night", version: 3 },
    },
    createdAt: iso({ days: -17 }),
    updatedAt: iso({ days: -10 }),
  },
];

export const demoDrafts: PlaylistDraft[] = [
  {
    id: "draft-1",
    ownerId: "user-lena",
    provider: "spotify",
    providerPlaylistId: "37i9dQZF1DX4JAvHpjipBk",
    canonicalUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4JAvHpjipBk",
    embedUrl: "https://open.spotify.com/embed/playlist/37i9dQZF1DX4JAvHpjipBk?utm_source=generator&theme=0",
    versions: [
      {
        provider: "spotify",
        providerPlaylistId: "37i9dQZF1DX4JAvHpjipBk",
        canonicalUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4JAvHpjipBk",
        embedUrl: "https://open.spotify.com/embed/playlist/37i9dQZF1DX4JAvHpjipBk?utm_source=generator&theme=0",
      },
      {
        provider: "apple-music",
        providerPlaylistId: "pl.u-b3b8V4etKZA9p",
        canonicalUrl: "https://music.apple.com/us/playlist/pl.u-b3b8V4etKZA9p",
        embedUrl: "https://embed.music.apple.com/us/playlist/pl.u-b3b8V4etKZA9p",
      },
    ],
    title: "Sunburn after dark",
    description: "Sticky drums, scorched guitars, and synths that refuse to cool down.",
    metadata: { providerTitle: "New Music Friday" },
    createdAt: iso({ days: -24 }),
    updatedAt: iso({ days: -4 }),
  },
  {
    id: "draft-2",
    ownerId: "user-lena",
    provider: "apple-music",
    providerPlaylistId: "pl.u-b3b8V4etKZA9p",
    canonicalUrl: "https://music.apple.com/us/playlist/pl.u-b3b8V4etKZA9p",
    embedUrl: "https://embed.music.apple.com/us/playlist/pl.u-b3b8V4etKZA9p",
    title: "Curtains moving",
    description: "A slow build for a room that has nowhere to be.",
    metadata: {},
    createdAt: iso({ days: -18 }),
    updatedAt: iso({ days: -2 }),
  },
  {
    id: "draft-3",
    ownerId: "user-lena",
    provider: "spotify",
    providerPlaylistId: "37i9dQZF1DX0XUsuxWHRQd",
    canonicalUrl: "https://open.spotify.com/playlist/37i9dQZF1DX0XUsuxWHRQd",
    embedUrl: "https://open.spotify.com/embed/playlist/37i9dQZF1DX0XUsuxWHRQd?utm_source=generator&theme=0",
    title: "Emergency glass",
    description: "Break only when the queue stalls.",
    metadata: { providerTitle: "RapCaviar" },
    createdAt: iso({ days: -14 }),
    updatedAt: iso({ days: -6 }),
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "notification-1",
    userId: "user-lena",
    kind: "assignment",
    title: "You’re up next",
    body: "Sunday Service drops in 2 days. Your playlist is ready to go.",
    href: "/app/clubs/sunday-service",
    createdAt: iso({ hours: -2 }),
  },
  {
    id: "notification-2",
    userId: "user-lena",
    kind: "theme",
    title: "New theme in Needle Exchange",
    body: "Heatwave at midnight — songs for a city still radiating after dark.",
    href: "/app/clubs/needle-exchange",
    createdAt: iso({ days: -1 }),
  },
  {
    id: "notification-3",
    userId: "user-lena",
    kind: "membership",
    title: "Theo joined Sunday Service",
    body: "Theo was added to the end of the rotation.",
    href: "/app/clubs/sunday-service",
    readAt: iso({ hours: -20 }),
    createdAt: iso({ days: -2 }),
  },
];

export const demoMessages: ChatMessage[] = [
  {
    id: "message-1",
    threadType: "club",
    threadId: "club-needle",
    authorId: "user-priya",
    authorName: "Priya Shah",
    authorInitials: "PS",
    body: "The transition at track six is outrageous in the best way.",
    reactions: [{ emoji: "🔥", userIds: ["user-lena", "user-theo"] }],
    createdAt: iso({ hours: -5 }),
  },
  {
    id: "message-2",
    threadType: "club",
    threadId: "club-needle",
    authorId: "user-theo",
    authorName: "Theo Brooks",
    authorInitials: "TB",
    body: "Already building around the new theme. It may get a little humid.",
    reactions: [{ emoji: "💿", userIds: ["user-marcus"] }],
    createdAt: iso({ hours: -3 }),
  },
  {
    id: "message-3",
    threadType: "drop",
    threadId: "drop-sunburn",
    authorId: "user-marcus",
    authorName: "Marcus Chen",
    authorInitials: "MC",
    body: "That opener made the whole description click immediately.",
    reactions: [{ emoji: "☀️", userIds: ["user-lena", "user-priya"] }],
    createdAt: iso({ days: -2, hours: -3 }),
  },
];

export function demoUserById(id: string) {
  return demoUsers.find((user) => user.id === id);
}
